OPSI-MAKEPACKAGE(1)
===================
:doctype: manpage


NAME
----
opsi-makepackage - commandline interface for opsi package creation.


SYNOPSIS
--------
*opsi-makepackage* ['OPTIONS'] ['SOURCE_DIRECTORY']

Provides an opsi package from a package source directory.
If no source directory is supplied, the current directory will be used.


DESCRIPTION
-----------
opsi-makepackage provides an opsi package from a package source directory.


OPTIONS
-------

*--quiet*, *-q*::
Do not show progress.

*--verbose*, *-v*::
Verbose output.

*--log-level* 'LEVEL', *-l* 'LEVEL'::
Set log level to 'LEVEL'.
Possible levels are: 0=nothing, 1=essential, 2=critical, 3=error, 4=warning, 5=notice, 6=info, 7=debug, 8=debug2, 9=confidential

*--no-compression*, *-n*::
Do not compress.

*--archive-format* [tar|cpio], *-F* [tar|cpio]::
Archive format to use. Defaults to "cpio".

*--follow-symlinks*, *-h*::
Follow symlinks.

*--custom-name* 'custom name', *-i* 'custom name'::
Add custom files and add custom name to the base package.

*--custom-only* 'custom name', *-c* 'custom name'::
Only package custom files and add custom name to base package.

*--temp-directory* 'DIRECTORY', *-t* 'DIRECTORY'::
Use 'DIRECTORY' as temp directory.

*--md5*, *-m*::
Create md5sum file. Default behaviour.

*--no-md5*::
Do not create file with md5 checksum.

*--zsync*, *-z*::
Create zsync file. Default behaviour.

*--no-zsync*::
Do not create zsync file.

*--no-pigz*::
Disable the usage of pigz for compression.


OPTIONS FOR PACKAGE VERSIONS
----------------------------

Set versions for package. Combinations are possible.

*--keep-versions*, *-k*::
Keep versions and overwrite package

*--package-version* 'PACKAGEVERSION'::
Set new package version

*--product-version* 'PRODUCTVERSION'::
Set new product version for package


AUTHOR
------
opsi-makepackage was created by Jan Schneider.
This manpage was written by Niko Wenselowski.


RESOURCES
---------
See <http://www.opsi.org/> for more information.


COPYING
-------
Copyright \(C) 2013-2018 uib GmbH.
This software is released under the GNU General Public License version 2.
