image: python:3.7-stretch

stages:
  - build
  - package

.install_tools: &install_tools |
  export DEBIAN_FRONTEND=noninteractive
  apt update
  apt -y install debhelper osc
  pip3 install --trusted-host pypi.uib.gmbh --index-url http://pypi.uib.gmbh:8080/simple opsi-dev-tools
  pip3 install poetry

build:linux-pyinstaller:
  stage: build
  script:
    - *install_tools  
    - apt -y install python3-newt gettext gzip asciidoc-base
    - poetry install
    - poetry run opsi-dev-tool -l info --pyinstaller-poetry-build
    - mv dist/opsi-utils .
    # Check if binary is working
    - opsi-utils/opsi-admin --version
  artifacts:
    name: 'opsi-utils-linux-pyinstaller'
    paths:
      - opsi-utils
    expire_in: 2 days

package:obs_int:
  stage: package
  dependencies:
    - build:linux-pyinstaller
  script:
    - *install_tools
    - python3 -m opsidevtools -l info --obs-update-package https://obs.uib.gmbh home:uibmz:opsi:4.2:experimental
#  only:
#      - /^release/.*$/i
#      - tags
#      - web

package:obs_ext:
  stage: package
  dependencies:
    - build:linux-pyinstaller
  script:
    - *install_tools
    - python3 -m opsidevtools -l info --obs-update-package https://build.opensuse.org home:uibmz:opsi:4.2:experimental
#  only:
#      - /^release/.*$/i
#      - tags
#      - web
