image: ubuntu:latest

stages:
  - build
  - package

build manpages:
  stage: build
  before_script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt install -y tzdata
    - apt install -y gzip asciidoc-base
  script:
    - ./recreate_manpages.sh
  artifacts:
    paths:
      - manpages/compiled/*
    expire_in: 2 days

package for OBS:
  stage: package
  before_script:
    - apt update
    - apt install -y devscripts debhelper gettext
  script:
    - ./create_source.sh
    - test -f opsi-utils_*.dsc
    - test -f opsi-utils_*.tar.gz
    - test -f opsi-utils.spec
  artifacts:
    paths:
      - opsi-utils_*.dsc
      - opsi-utils_*.tar.gz
      - opsi-utils.spec
    expire_in: 2 days
  only:
      - /^release/.*$/i
      - tags
      - web
