image: python:3.7-stretch

stages:
  - build
  - package

build:linux-pyinstaller:
  stage: build
  script:
    - apt update
    - apt -y upgrade
    - apt -y install curl python3-newt gettext
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
    - source $HOME/.poetry/env
    - ./pyinstaller-build.py
    - mv dist/opsi-utils .
  artifacts:
    name: 'opsi-utils-linux-pyinstaller'
    paths:
      - opsi-utils
    expire_in: 2 days

build:linux-manpages:
  stage: build
  before_script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt install -y tzdata
    - apt install -y gzip asciidoc-base
  script:
    - ./recreate_manpages.sh
  artifacts:
    paths:
      - manpages/compiled/*
    expire_in: 2 days

package:deb:
  stage: package
  dependencies:
    - build:linux-pyinstaller
  script:
    - apt update
    - apt -y upgrade
    - apt -y install debhelper
    - deps=$((dpkg-checkbuilddeps 2>&1 | sed "s/dpkg-checkbuilddeps\:\serror\:\sUnmet build dependencies\://g" | sed "s/[\(][^)]*[\)] //g") || echo -n "")
    - echo $deps
    - test -z "$deps" || apt -y install $deps
    - dpkg-buildpackage -b
    - mkdir deb
    - mv ../opsi-utils_*.deb deb/

  artifacts:
    name: 'opsi-utils-deb'
    paths:
      - deb/*
    expire_in: 2 day


#package for OBS:
#  stage: package
#  before_script:
#    - apt update
#    - apt install -y devscripts debhelper gettext
#  script:
#    - ./create_source.sh
#    - test -f opsi-utils_*.dsc
#    - test -f opsi-utils_*.tar.gz
#    - test -f opsi-utils.spec
#  artifacts:
#    paths:
#      - opsi-utils_*.dsc
#      - opsi-utils_*.tar.gz
#      - opsi-utils.spec
#    expire_in: 2 days
#  only:
#      - /^release/.*$/i
#      - tags
#      - web
