image: docker.uib.gmbh/opsi/dev/pybuilder:deb9-py3.13

variables:
  SKIP_TESTS: "false"

stages:
  - test
  - build
  - integration_test
  - publish

test-and-lint:
  stage: test
  tags:
    - docker-x64
  script:
    - export UV_PYTHON_PREFERENCE="only-managed"
    - export UV_PYTHON="3.13-x86_64"
    - apt update
    - apt -y install python3-newt gettext gzip asciidoc-base zstd
    - uv sync --frozen
    - uv run ruff check opsiutils tests
    - uv run mypy opsiutils tests
    - uv run pytest -x --tb=short -o junit_family=xunit2 --junitxml=testreport.xml --cov-append --cov opsiutils --cov-report term --cov-report xml -v tests
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # dont run on merge-requests
      when: never
    - if: $SKIP_TESTS == "false"

build:linux-x64:
  stage: build
  tags:
    - docker-x64
  script:
    - export UV_PYTHON_PREFERENCE="only-managed"
    - export UV_PYTHON="3.13-x86_64"
    - TRANSIFEX_MIN_REVIEW_RATE=0.0
    - '[ "$CI_COMMIT_TAG" = "" ] || TRANSIFEX_MIN_REVIEW_RATE=1.0'
    - apt update
    - apt -y install python3-newt gettext gzip asciidoc-base zstd
    - curl -sS "${OPSIDEVTOOLS_INSTALLER_URL_LINUX_X64}" | sh
    - uv self update
    - uv sync --frozen
    - uv run opsi-dev-cli -l info pyinstaller build
    - '[ "$CI_COMMIT_TAG" = "" ] && uv run opsi-dev-cli -l info binary push dist/opsi-utils --prerelease="$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || uv run opsi-dev-cli -l info binary push dist/opsi-utils'
    - mv dist/opsi-utils ./opsi-utils-amd64
    # Check if binary is working
    - opsi-utils-amd64/opsi-admin --version
    - opsi-dev-cli -l info binary pull
    - mv opsi-cli opsi-utils-amd64/
    - ls -l opsi-utils-amd64/
  artifacts:
    name: "opsi-utils-linux-pyinstaller"
    paths:
      - opsi-utils-amd64
    expire_in: 2 days

build:linux-arm64:
  stage: build
  tags:
    - docker-arm64
  script:
    - export UV_PYTHON_PREFERENCE="only-managed"
    - export UV_PYTHON="3.13-aarch64"
    - TRANSIFEX_MIN_REVIEW_RATE=0.0
    - '[ "$CI_COMMIT_TAG" = "" ] || TRANSIFEX_MIN_REVIEW_RATE=1.0'
    - apt update
    - apt -y install python3-newt gettext gzip asciidoc-base zstd
    - curl -sS "${OPSIDEVTOOLS_INSTALLER_URL_LINUX_ARM64}" | sh
    - uv self update
    - uv sync --frozen
    - uv run opsi-dev-cli -l info pyinstaller build
    - mv dist/opsi-utils ./opsi-utils-arm64
    # Check if binary is working
    - OPSI_HOSTNAME=test.uib.local opsi-utils-arm64/opsi-admin --version
    - opsi-dev-cli -l info binary pull
    - mv opsi-cli opsi-utils-arm64/
    - ls -l opsi-utils-arm64/
  artifacts:
    name: "opsi-utils-arm64-pyinstaller"
    paths:
      - opsi-utils-arm64
    expire_in: 2 days

integration_test:
  tags:
    - docker-x64
  services:
    - name: mysql:8.3
      command:
        - --max_connections=1000
        # - --mysql-native-password=ON
        - --default-authentication-plugin=mysql_native_password
    - name: redislabs/redistimeseries:latest
      alias: redis
  variables:
    MYSQL_ROOT_PASSWORD: "opsi"
    MYSQL_DATABASE: "opsitest"
    MYSQL_USER: "opsi"
    MYSQL_PASSWORD: "opsi"
    MYSQL_HOST: mysql
    REDIS_HOST: redis
    OPSI_ADMIN_PASSWORD: vhahd8usaz
    OPSI_HOST_ROLE: configserver
    OPSI_HOST_ID: "test.uib.gmbh"
    OPSI_TFTPBOOT: "false"
    OPSICONFD_LOG_LEVEL: 6
    OPSICONFD_RESTORE_BACKUP_URL: "http://binaryindex.uib.gmbh/development/testbackup/all/all/testbackup_all_all_1.1.tar.gz"
  stage: integration_test
  image:
    name: docker.uib.gmbh/opsi/opsi-server:4.3-development
    entrypoint: [""]
  script:
    - bash /entrypoint.sh &
    - while ! nc -v -z -w3 localhost 4447 > /dev/null 2>&1; do sleep 1; done
    - source /entrypoint.sh set_environment_vars # to set hosts for redis/grafana
    - apt update
    - apt -y install zstd
    - for file in integration_tests/*.sh; do echo "=== Running $file ==="; bash "$file"; done
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # dont run on merge-requests
      when: never
    - if: $SKIP_TESTS == "false"

obs_ext:
  tags:
    - docker-x64
  stage: publish
  script:
    - curl -sS "${OPSIDEVTOOLS_INSTALLER_URL_LINUX_X64}" | sh
    - opsi-dev-cli -l info packaging obs update-package https://build.opensuse.org home:uibmz:opsi:4.3:development
    - opsi-dev-cli -l info changelog from-git output/
    - opsi-dev-cli release-service register-package-version opsi-utils SERVER_PACKAGE --changelog-file output/changelog.md
    - opsi-dev-cli release-service push-repository-state opsi-utils SERVER_PACKAGE SERVER_PACKAGE-4.3-development
  rules:
    - if: "$CI_COMMIT_TAG != null"
