image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-3.10

stages:
  - test
  - build
  - publish


pytest-pylint:
  stage: test
  script:
    - apt -y install python3-newt gettext gzip asciidoc-base
    - poetry lock --no-update --no-cache
    - poetry install
    - poetry run pylint --disable=R,fixme opsiutils
    - poetry run pytest --tb=short -o junit_family=xunit2 --junitxml=testreport.xml --cov-append --cov opsiutils --cov-report term --cov-report xml -v tests


linux-pyinstaller:
  stage: build
  script:
    - apt -y install python3-newt gettext gzip asciidoc-base
    - poetry lock --no-update --no-cache
    - poetry install
    - poetry run opsi-dev-cli -l info pyinstaller build
    - '[ "$CI_COMMIT_TAG" = "" ] && poetry run opsi-dev-cli -l info binary push dist/opsi-utils --prerelease="$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || poetry run opsi-dev-cli -l info binary push dist/opsi-utils'
    - mv dist/opsi-utils ./opsi-utils-amd64
    # Check if binary is working
    - opsi-utils-amd64/opsi-admin --version
    - opsi-dev-cli -l info binary pull
    - mv opsi-cli opsi-utils-amd64
  artifacts:
    name: 'opsi-utils-linux-pyinstaller'
    paths:
      - opsi-utils-amd64
    expire_in: 2 days

arm64-pyinstaller:
  stage: build
  tags:
    - arm64
  script:
    - apt -y install python3-newt gettext gzip asciidoc-base
    - poetry lock --no-update --no-cache
    - poetry install
    - poetry run opsi-dev-cli -l info pyinstaller build
    - mv dist/opsi-utils ./opsi-utils-arm64
    # Check if binary is working
    - OPSI_HOSTNAME=test.uib.local opsi-utils-arm64/opsi-admin --version
    - opsi-dev-cli -l info binary pull
    - mv opsi-cli opsi-utils-arm64
  artifacts:
    name: 'opsi-utils-arm64-pyinstaller'
    paths:
      - opsi-utils-arm64
    expire_in: 2 days

obs_ext:
  stage: publish
  script:
    - opsi-dev-tool -l info --obs-update-package https://build.opensuse.org home:uibmz:opsi:4.2:development
  only:
    - tags
