image: python:3.7-stretch

stages:
  - build
  - package

build:linux-pyinstaller:
  stage: build
  script:
    - apt update
    - apt -y upgrade
    - apt -y install curl python3-newt gettext gzip asciidoc-base
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
    - source $HOME/.poetry/env
    - poetry install
    - poetry run opsi-dev-tool -l info --pyinstaller-poetry-build
    - mv dist/opsi-utils .
    # Check if binary is working
    - opsi-utils/opsi-admin --version
  artifacts:
    name: 'opsi-utils-linux-pyinstaller'
    paths:
      - opsi-utils
    expire_in: 2 days

#package:deb:
#  stage: package
#  dependencies:
#    - build:linux-pyinstaller
#  script:
#    - apt update
#    - apt -y upgrade
#    - apt -y install debhelper
#    - deps=$((dpkg-checkbuilddeps 2>&1 | sed "s/dpkg-checkbuilddeps\:\serror\:\sUnmet build dependencies\://g" | sed "s/[\(][^)]*[\)] //g") || echo -n "")
#    - echo $deps
#    - test -z "$deps" || apt -y install $deps
#    - dpkg-buildpackage -b
#    - mkdir deb
#    - mv ../opsi-utils_*.deb deb/
#
#  artifacts:
#    name: 'opsi-utils-deb'
#    paths:
#      - deb/*
#    expire_in: 2 day

package:obs:
  stage: package
  dependencies:
    - build:linux-pyinstaller
  script:
    - apt update
    - apt -y install debhelper osc
    - pip3 install --trusted-host pypi.uib.gmbh --index-url http://pypi.uib.gmbh:8080/simple opsi-dev-tools
    - python3 -m opsidevtools -l info --obs-update-package https://obs.uib.local home:uibmz:opsi:4.2:experimental
#  only:
#      - /^release/.*$/i
#      - tags
#      - web
