image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-3.10

stages:
  - test
  - build
  - publish


test:pytest-pylint:
  stage: test
  script:
    - apt -y install python3-newt gettext gzip asciidoc-base
    - poetry config experimental.new-installer false
    - poetry lock --no-update
    - poetry install
    - poetry run pylint --disable=R,fixme opsiutils


build:linux-pyinstaller:
  stage: build
  script:
    - apt -y install python3-newt gettext gzip asciidoc-base
    - poetry config experimental.new-installer false
    - poetry lock --no-update
    - poetry install
    - poetry run opsi-dev-tool -l info --pyinstaller-poetry-build
    - '[ "$CI_COMMIT_TAG" = "" ] && poetry run opsi-dev-tool -l info --binary-push dist/opsi-utils "$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || poetry run opsi-dev-tool -l info --binary-push dist/opsi-utils'
    - mv dist/opsi-utils ./opsi-utils-amd64
    # Check if binary is working
    - opsi-utils-amd64/opsi-admin --version
  artifacts:
    name: 'opsi-utils-linux-pyinstaller'
    paths:
      - opsi-utils-amd64
    expire_in: 2 days


build:arm64-pyinstaller:
  stage: build
  tags:
    - arm64
  script:
    - apt -y install python3-newt gettext gzip asciidoc-base
    - poetry config experimental.new-installer false
    - poetry lock --no-update
    - poetry install
    - poetry run opsi-dev-tool -l info --pyinstaller-poetry-build
    - mv dist/opsi-utils ./opsi-utils-arm64
    # Check if binary is working
    - OPSI_HOSTNAME=test.uib.local opsi-utils-arm64/opsi-admin --version
  artifacts:
    name: 'opsi-utils-arm64-pyinstaller'
    paths:
      - opsi-utils-arm64
    expire_in: 2 days


package:obs_int:
  stage: publish
  script:
    - opsi-dev-tool -l info --obs-update-package https://obs.uib.gmbh home:uibmz:opsi:4.2:development
  only:
    - tags


package:obs_ext:
  stage: publish
  script:
    - opsi-dev-tool -l info --obs-update-package https://build.opensuse.org home:uibmz:opsi:4.2:development
  only:
    - tags
