#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
   = = = = = = = = = = =
   =   opsi-convert    =
   = = = = = = = = = = =
   
   opsi-convert is part of the desktop management solution opsi
   (open pc server integration) http://www.opsi.org
   
   Copyright (C) 2007, 2008 uib GmbH
   
   http://www.uib.de/
   
   All rights reserved.
   
   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License version 2 as
   published by the Free Software Foundation.
   
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
   
   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
   
   @copyright:	uib GmbH <info@uib.de>
   @author: Jan Schneider <j.schneider@uib.de>
   @license: GNU General Public License version 2
"""

__version__ = '3.5'

import sys

# OPSI imports
from OPSI.Logger import *
from OPSI.Backend.MySQL import MySQLBackend
from OPSI.Backend.File31 import File31Backend
from OPSI.Backend.Replicator import BackendReplicator

logger = Logger()
logger.setConsoleLevel(LOG_ERROR)
logger.setConsoleFormat('%M')
logger.setFileFormat('%D [%L] %M')
logger.setConsoleColor(True)


class OpsiConvert():
	def __init__(self, readBackend, writeBackend):
		self.readBackend  = readBackend
		self.writeBackend = writeBackend
		
		self.backendReplicator = BackendReplicator(
			readBackend  = self.readBackend,
			writeBackend = self.writeBackend,
			newServerId  = None,
			cleanupFirst = True)
			
		self.currentProgressSubject = self.backendReplicator.getCurrentProgressSubject()
		self.overallProgressSubject = self.backendReplicator.getOverallProgressSubject()
		
		self.currentProgressSubject.attachObserver(self)
		self.overallProgressSubject.attachObserver(self)
		
	def convert(self):
		self.backendReplicator.replicate()
		
	def __del__(self):
		self.currentProgressSubject.detachObserver(self)
		self.overallProgressSubject.detachObserver(self)
	
	def messageChanged(self, subject, message):
		print message
	
	def progressChanged(self, subject, state, percent, timeSpend, timeLeft, speed):
		#print subject, state, timeLeft
		#sys.stdout.write("%s %0.2f%% ETA: %ds\n" % (subject.getId(), percent, timeLeft))
		sys.stdout.write("                                    %s %0.2f%% ETA: %ds          \r" % (subject.getId(), percent, timeLeft))
		sys.stdout.flush()
		


readBackend  = MySQLBackend(username = 'opsi', password = 'opsi', database='opsi')
writeBackend = File31Backend()

oc = OpsiConvert(readBackend, writeBackend)
oc.convert()

print "done"

