[tool.poetry]
name = "opsi-utils"
version = "4.2.0.25"
description = "Utilities for working with opsi"
homepage = "https://www.opsi.org"
license = "AGPL-3.0"
maintainers = ["uib GmbH <info@uib.de>"]
authors = ["uib GmbH <info@uib.de>"]
packages = [
    { include = "opsiutils" }
]
include = [
    "opsi-utils_data/**/*"
]

[[tool.poetry.source]]
name = "uibpypi"
url = "http://pypi.uib.gmbh:8080/simple"

[tool.poetry.dependencies]
python = "^3.7"
#python-opsi = {path = "python-opsi"}
python-opsi = "^4.2.0.60"
python-magic = "^0.4.15"
orjson = "^2.6.5"
mysqlclient = "^1.4.6"
psutil = "^5.7.0"
distro = {platform = "linux", version = "^1.5.0"}
ldap3 = "2.7"

[tool.poetry.dev-dependencies]
opsi-dev-tools = "^1.0"
pyinstaller = "^4.0"

[tool.poetry.scripts]
opsi-admin = "opsiutils.opsiadmin:main"
opsi-backup = "opsiutils.opsibackup:main"
opsi-convert = "opsiutils.opsiconvert:main"
opsi-makepackage = "opsiutils.opsimakepackage:main"
opsi-newprod = "opsiutils.opsinewprod:main"
opsi-package-manager = "opsiutils.opsipackagemanager:main"
opsi-package-updater = "opsiutils.opsipackageupdater:main"
opsi-setup = "opsiutils.opsisetup:main"
opsi-python = "opsiutils.opsipython:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
