[tool.poetry]
name = "opsiutils"
version = "4.2.0"
description = ""
authors = ["Jan Schneider <j.schneider@uib.de>"]

[[tool.poetry.source]]
name = "uibpypi"
url = "http://pypi.uib.gmbh:8080/simple"

[tool.poetry.dependencies]
python = "^3.7"
python-opsi = "^4.2.0"
python-magic = "^0.4.15"
orjson = "^2.6.5"
mysqlclient = "^1.4.6"

[tool.poetry.dev-dependencies]
pyinstaller = "^3.6"

[tool.poetry.scripts]
opsi-admin = "opsiutils.opsiadmin:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
