[tool.poetry]
name = "opsi-utils"
version = "4.2.0"
description = ""
authors = ["Jan Schneider <j.schneider@uib.de>"]

[[tool.poetry.source]]
name = "uibpypi"
url = "http://pypi.uib.gmbh:8080/simple"

[tool.poetry.dependencies]
python = "^3.7"
python-opsi = "^4.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
