[project]
name = "opsi-utils"
version = "4.3.15.0"
description = "Utilities for working with opsi"
readme = "README.md"
license = "AGPL-3.0-only"
requires-python = ">=3.11"
dependencies = [
	"python-opsi>=4.3,<4.4",
	"python-opsi-common>=4.3.30.1,<4.4",
	"python-magic>=0.4",
	"annotated-types>=0.7",
	"configupdater>=3.1",
	"paramiko>=3.2",
	"pydantic-core>=2.18",
	"pyzsync>=1.2",
]

[[project.authors]]
name = "uib GmbH"
email = "info@uib.de"

[[project.maintainers]]
name = "uib GmbH"
email = "info@uib.de"

[dependency-groups]
dev = [
	"distro>=1.5",
	"mypy>=1.0",
	"pyinstaller>=6.10",
	"pytest>=8.1",
	"pytest-cov>=6.0",
	"ruff>=0.8",
]

[project.urls]
Homepage = "https://www.opsi.org"

[project.scripts]
opsi-admin = "opsiutils.opsiadmin:main"
opsi-backup = "opsiutils.opsibackup:main"
opsi-convert = "opsiutils.opsiconvert:main"
opsi-makepackage = "opsiutils.opsimakepackage:main"
opsi-newprod = "opsiutils.opsinewprod:main"
opsi-package-manager = "opsiutils.opsipackagemanager:main"
opsi-package-updater = "opsiutils.opsipackageupdater:main"
opsi-setup = "opsiutils.opsisetup:main"
opsi-python = "opsiutils.opsipython:main"
opsi-wakeup-clients = "opsiutils.opsiwakeupclients:main"
opsi-outdated-to-setup = "opsiutils.opsioutdatedtosetup:main"

[tool.uv]
extra-index-url = ["https://pypi.uib.gmbh/simple"]
index-strategy = "unsafe-best-match"
package = true

[tool.mypy]
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
follow_imports = "silent"

[tool.ruff]
line-length = 140
target-version = "py311"

[tool.ruff.format]
indent-style = "tab"

[tool.setuptools.package-data]
opsiutils_data = ["*"]

[tool.setuptools.packages.find]
include = ["opsiutils", "opsiutils.*", "opsiutils_data", "opsiutils_data.*"]
